name: Build & Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: |
        dotnet tool restore
        dotnet restore
        npm install

    - name: Test
      run: dotnet test --verbosity normal test

    - name: Build
      run: |
        dotnet fable src/Worker -o worker-out
        dotnet fable src/App
        npx vite build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: deploy
