name: Build & Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: |
        dotnet restore
        npm install

    - name: Test
      run: dotnet test --verbosity normal test

    - name: Build
      run: |
        dotnet fable worker -o worker-out
        dotnet fable src
        npx vite build
